---
repos:
  - repo: local
    hooks:
      - id: pip-compile
        name: pip-compile
        description: "Automatically run 'uv pip compile' on your requirements"
        entry: uv pip compile
        language: python
        files: ^requirements\.(in|txt)$
        args: []
        pass_filenames: false
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"

      - id: uv-lock
        name: uv-lock
        description: "Automatically run 'uv lock' on your project dependencies"
        entry: uv lock
        language: python
        files: ^(uv\.lock|pyproject\.toml|uv\.toml)$
        args: []
        pass_filenames: false
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"

      - id: uv-export
        name: uv-export
        description: "Automatically run 'uv export' on your project dependencies"
        entry: uv export
        language: python
        files: ^uv\.lock$
        args: ["--frozen", "--output-file=requirements.txt"]
        pass_filenames: false
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"

      - id: uv-sync
        name: uv-sync
        description: "Automatically run 'uv sync' on your repository after a checkout, pull or rebase"
        entry: uv sync
        args: ["--locked"]
        language: python
        always_run: true
        pass_filenames: false
        stages: [post-checkout, post-merge, post-rewrite]
        minimum_pre_commit_version: "2.9.2"

      - id: ruff
        name: ruff-check
        description: "Check Ruff lint"
        entry: ruff
        require_serial: true
        types_or: [cython, pyi, python]
        language: system

      - id: mypy
        name: mypy-formating
        description: "Check mypy lint"
        entry: mypy
        require_serial: true
        types_or: [cython, pyi, python]
        language: system

      - id: isort
        name: isort-formating
        description: "Sort imports"
        entry: isort
        require_serial: true
        types_or: [cython, pyi, python]
        args: ["--profile", "black", "--filter-files"]
        language: system

      - id: black
        name: black-check
        description: "Reformat code with black"
        entry: black
        require_serial: true
        types_or: [python, pyi]
        language: system

      - id: pytest-check
        name: pytest-check
        description: "Check code with pytest"
        entry: pytest
        args: ["-vv", "-x", "-s", "--cov=.", "--cov-report", "term-missing"]
        language: system
        pass_filenames: false

      - id: bandit-check
        name: bandit-check
        description: "Check code with bandit"
        entry: bandit
        args: ["-r", "*"]
        language: system
        pass_filenames: false

      - id: pip-audit
        name: pip-audit
        description: Checks you files for CVEs.
        entry: pip-audit
        args: ["-r", "requirements.txt"]
        language: system
        pass_filenames: false

      - id: gitlint
        name: gitlint
        description: Checks your git commit messages for style.
        language: python
        additional_dependencies: ["./gitlint-core[trusted-deps]"]
        entry: gitlint
        args: [--staged, --msg-filename]
        stages: [commit-msg]
