---
version: "3"
services:
    flask:
        build: .
        volumes:
            - "./src:/flask_test"
        ports:
            - 8000:8000
        env_file:
            - .env
        networks:
            - database_net
            - web_net
    db:
        image: "postgres"
        volumes:
            - dbdata:/var/lib/postgresql/data
        env_file:
            - .env_db
        networks:
            - database_net
    nginx:
        image: "nginx"
        ports:
            - "8080:80"
        volumes:
            - ./conf/nginx:/etc/nginx/conf.d/
        networks:
            - web_net
networks:
    database_net:
        driver: bridge
    web_net:
        driver: bridge
volumes:
    dbdata:
