[tool.poetry]
name = "flask_test"
version = "0.1.0"
description = ""
authors = ["Martins Golvers <martins.golvers@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
Flask-Login = "^0.6.2"
Flask-Migrate = "^4.0.4"
Flask-WTF = "^1.1.1"
Flask-Bootstrap = "^3.3.7.1"
gunicorn = "^20.1.0"
psycopg2 = "^2.9.6"
Flask-SQLAlchemy = "^3.0.3"
python-dotenv = "^1.0.0"
flask = "^2.3.2"
wtforms = "^3.0.1"
wtforms-sqlalchemy = "^0.3"
email-validator = "^2.0.0.post2"

[tool.poetry.group.dev.dependencies]
pytest-sugar = "^0.9.7"
pytest-clarity = "^1.0.1"
pytest-icdiff = "^0.6"
pytest = "^7.3.1"
pylint = "^2.17.3"
pytest-cov = "^4.0.0"
bandit = "^1.7.5"
flask-testing = "^0.8.1"
flake8 = "^6.0.0"
isort = "^5.12.0"
black = "^23.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | \.venv
  | __pycache__
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 100
force_single_line = true

[tool.autopep8]
max_line_length = 100

[tool.pylint]
max-line-length-suggestions = 100

[tool.flake8]
max_line_length = 100

[tool.pyright]

[tool.pydocstyle]

[tool.pytest.ini_options]
testpaths = "tests"
python_files = "test_*.py"
python_functions = "test_*"
python_classes = "Test* *Tests"
addopts = "-vv -x -s --cov=. --cov-report term-missing"
asyncio_mode = "auto"
